import type { LucideIcon } from "lucide-react";
import {
  Banknote,
  FileText,
  Wallet,
  Landmark,
  Smartphone,
  Zap,
  Tv,
  Droplet,
  Flame,
  Shield,
  CreditCard,
  Fingerprint,
  Building2,
  Users,
  Receipt,
  GraduationCap,
  Car,
  Home,
  Gift,
  Cable,
  Gauge,
  Wifi,
  BatteryCharging,
  Building,
  ScrollText,
} from "lucide-react";

const ICONS: Record<string, LucideIcon> = {
  CASH_WITHDRAW: Banknote,
  MINI_STATEMENT: FileText,
  CASH_DEPOSIT: Wallet,
  BALANCE_ENQUIRY: Landmark,
  UPI_CASH_POINT: Smartphone,
  MONEY_TRANSFER: Banknote,
  CASH_COLLECTION: Wallet,
  LOANS: Landmark,
  INSURANCE: Shield,
  CREDIT_CARDS: CreditCard,
  MOBILE_PREPAID: Smartphone,
  LOAN_REPAYMENT: Landmark,
  ELECTRICITY: Zap,
  DTH: Tv,
  AGENT_COLLECTION: Wallet,
  CREDIT_CARD_BILL: CreditCard,
  FASTAG_RECHARGE: Car,
  MOBILE_POSTPAID: Smartphone,
  WATER: Droplet,
  LANDLINE_POSTPAID: Smartphone,
  GAS_PIPELINE: Flame,
  INSURANCE_PREMIUM: Shield,
  BROADBAND_POSTPAID: Wifi,
  SUBSCRIPTION: ScrollText,
  EDUCATION_FEES: GraduationCap,
  LPG_CYLINDER: Flame,
  MUNICIPAL_TAXES: Building2,
  ECHALLAN: Car,
  CABLE_TV: Cable,
  DONATION: Gift,
  MUNICIPAL_SERVICES: Building2,
  PREPAID_METER: Gauge,
  NCMC_RECHARGE: CreditCard,
  FLEET_CARD_RECHARGE: Car,
  EV_RECHARGE: BatteryCharging,
  HOUSING_SOCIETY: Home,
  LIC: Shield,
  RENTAL: Home,
  CLUBS_AND_ASSOCIATIONS: Users,
  LIC_SUVIDHA: Shield,
  AADHAAR_PAY: Fingerprint,
  APPLY_EPAN: Building,
  SHG_WITHDRAW_CASH: Wallet,
  SHG_DEPOSIT_CASH: Wallet,
};

export function getServiceIcon(code: string): LucideIcon {
  return ICONS[code] ?? Receipt;
}

const CATEGORY_ICONS: Record<string, LucideIcon> = {
  landmark: Landmark,
  receipt: Receipt,
  fingerprint: Fingerprint,
  "building-2": Building2,
  users: Users,
};

export function getCategoryIcon(icon: string | null): LucideIcon {
  return (icon && CATEGORY_ICONS[icon]) || Receipt;
}
